global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'discovery-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['discovery-server:8000']
        labels:
          application: 'Discovery Server Application'
  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service:8080']
        labels:
          application: 'Api Gateway Service Application'
  - job_name: 'passenger-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'passenger-service:8001' ]
        labels:
          application: 'Passenger Service Application'
  - job_name: 'driver-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'driver-service:8002' ]
        labels:
          application: 'Driver Service Application'
  - job_name: 'rides-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'rides-service:8003' ]
        labels:
          application: 'Rides Service Application'
  - job_name: 'rating-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'rating-service:8004' ]
        labels:
          application: 'Rating Service Application'
  - job_name: 'promo-code-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'promo-code-service:8006' ]
        labels:
          application: 'Promo-code Service Application'
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'payment-service:8005' ]
        labels:
          application: 'Payment Service Application'