server:
  port: 8003
spring:
  application:
    name: rides-service
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/rides
    username: ponchik18
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/main-change-log.yml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka