server:
  port: 8003
spring:
  application:
    name: rides-service
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/rides
    username: ponchik18
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/main-change-log.yml
  kafka:
    bootstrap-servers: localhost:9092
    sent-topic: create-ride
    accepted-topic: save-ride
    group_id: rides-service

#    consumer:
#      group-id: rides-service
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      auto-offset-reset: earliest
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    admin:
#      auto-create: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka