server:
  port: 8005
spring:
  application:
    name: payment-service
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/payment
    username: ponchik18
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/main-change-log.yml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
    fetch-registry: true
    register-with-eureka: true

stripe:
  apiKey: ${STRIPE_API_KEY}
feign-client:
  driver-service: http://driver-service
  passenger-service: http://passenger-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true