server:
  port: 8005
spring:
  application:
    name: payment-service
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/payment
    username: ponchik18
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/main-change-log.yml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka

stripe:
  apiKey: sk_test_51OHgpWDDm1iJ272hRAaQmTFcWzC7OuiAIcxw2RoxMRoZJCRho2ogQSdODX6CcnnlC2b9M7G2mB7KAM74cajW9Wrn002FnlpF48
  publicKey: pk_test_51OHgpWDDm1iJ272hIy7L2VITJb6dR4r6Ys9dMMDwXmf7qpFurxqsMiQt2LpoonSetfPscdA2fuakkOE7PShiuSqc00wl4seVRg